### PR TITLE
fix: serial head execution

### LINKED ISSUE #4785: Can't access meta tags from matched routes in head
### Which project does this relate to?

Router

### Describe the bug

Image

### Your Example Website or App

https://meta--tanstack-start-basic.netlify.app/meta/title

### Steps to Reproduce the Bug or Issue

Demo: https://meta--tanstack-start-basic.netlify.app/meta/title (using the meta title from the parent)
Repo (branch meta): https://github.com/juliomuhlbauer/tanstack-start-basic/tree/meta

### Expected behavior

Get the meta tags

### Screenshots or Videos

_No response_

### Platform

- Router / Start Version: 1.129.8
- OS: Windows 10
- Browser: Chrome
- Browser Version: 138.0.7204.169
- Bundler: Vite
- Bundler Version: 7

### Additional context

_No response_

### LINKED ISSUE #4889: Context is still empty when running the `head()` function.
### Which project does this relate to?

Router

### Describe the bug

If you add something to the context via `beforeLoad()`, it will not be available inside `head()` after a full-page reload (F5). It will only be available after subsequent navigations (via `<Link>` for example).

### Example

```tsx
// routes/(app)/index.tsx
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/(app)/")({
  beforeLoad: () => {
    return {
      getTitle: () => `Home`,
    };
  },
  component: Index,
});

function Index() {
  return (
    <h3>Welcome Home!</h3>
  );
}
```
```tsx
// routes/__root.tsx
interface MyRouterContext {
  getTitle?: () => string;
  queryClient: QueryClient;
}

export const Route = createRootRouteWithContext<MyRouterContext>()({
  head: ({ matches }) => {
    const title = matches
      .filter((match) => match.context.getTitle)
      .reduce((acc, { context }) => {
        const title = context.getTitle!();
        return acc ? `${acc} - ${title}` : title;
      }, "");

    return {
      meta: [
        {
          title: `${title}`, // will be empty on a full-page reload
        },
      ],
    };
  },
  component: RootComponent,
});

function RootComponent() {
  return (
    <>
      <HeadContent />
      <Outlet />
      <Scripts />
      <TanStackRouterDevtools position="bottom-right" />
    </>
  );
}
```

### Your Example Website or App

https://nbwiowazwkgithub-athu--3000--96435430.local-credentialless.webcontainer.io/

### Steps to Reproduce the Bug or Issue

Create a simple project and use the code given in the example.
Notice the page title isn't set to "Home" on a full-page reload.

### Expected behavior

In the given example, I expected the page title to be set to "Home" after a full-page reload (F5).

### Screenshots or Videos

_No response_

### Platform

```
{
  "dependencies": {
    "@tanstack/react-router": "^1.130.12",
    "@tanstack/react-router-devtools": "^1.130.13",
    "react": "^19.1.0",
    "react-dom": "^19.1.0",
  },
}
```

### Additional context

_No response_

### LINKED ISSUE #6085: notFound() won't emit head data if `__root` has an async loader
### Which project does this relate to?

Router

### Describe the bug

when having a route's loader throw notFound, the not found page is rendered without head if the `__root` route's `loader` is not complete.

### Your Example Website or App

https://github.com/paperclover/bug-reproductions/tree/tanstack-start-head-omitted

### Steps to Reproduce the Bug or Issue

- `npm i`
- `npm run dev`
- open `http://localhost:3000`, navigate to see css exists
- open `http://localhost:3000/not-found` on new tab, no css

### Expected behavior

to wait for __root's loader and render the head data.

### Screenshots or Videos

_No response_

### Platform

- Router / Start Version: 1.130.2 / 1.135.2
- OS: macOS
- Browser: N/A
- Browser Version: N/A
- Bundler: vite
- Bundler Version: ^7.1.7

### Additional context

blocking a pr at work to properly handle some 404 cases where we are actually showing our ErrorComponent

### PR DESCRIPTION
**Pull request by schiller-manuel**
fixes #6085
fixes #4785
fixes #4889

## Summary by CodeRabbit

* **Bug Fixes**
  * Router waits for all loaders to settle, defers applying head metadata until after loaders complete, logs head errors without stopping other heads, and improves redirect and 404 handling.
* **Chores**
  * Removed the not-found "via-head" route and its UI links; removed related prerender exclusion entries.
* **Tests**
  * E2E not-found tests narrowed to loader-only thrower scenarios (removed head thrower).

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/router-core/src/load-matches.ts [hunk 1]
```diff
@@ -931,7 +897,47 @@ export async function loadMatches(arg: {
...
+        console.error(`Error executing head for route ${routeId}:`, err)
+      }
+    }
+
+    // After head execution, check for notFound errors and throw the first one
+    for (const err of failures) {
+      if (isNotFound(err)) {
+        throw err
+      }
+    }
```
Comment (Sheraff) [inline packages/router-core/src/load-matches.ts]: I find it a little curious that we call `executeHead` for children of a `match` that would have thrown a `notFound`

If we have `/a/b/c` and `/b` throws a `notFound` it its `loader`, should we really still execute the `head` of `/c`? It feels "leaky"
