### PR TITLE
fix(react-router,solid-router): top-level `Matches` should use `pendingComponent` on root route

### LINKED ISSUE #2317: Pending component doesn't work on root route
### Which project does this relate to?

Router

### Describe the bug

I've noticed the pending component doesn't stay mounted if it's on the __root route. It seems like it does quickly render but doesn't stay until the __root `loader` method is finished, instead it instantly unmounts

### Your Example Website or App

https://codesandbox.io/p/devbox/epic-shape-z676nh

### Steps to Reproduce the Bug or Issue

1. Verify that you see a green box on first load to verify that non __root pending component works
2. Go to `src\routes\index.tsx` and comment out the pending component and loader
3. Go to `src\routes\__root.tsx` and uncomment the same code from previous file
4. Verify that the green box does not appear after refreshing window

### Expected behavior

I expect to see the green box upon loading after the 4th repro step. I've left a red box as the router's default pending component to show that does seem to be working normally in all relevant cases

### Screenshots or Videos

_No response_

### Platform

- Version: 1.57.8

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TkDodo**
fixes #2317

## Summary by CodeRabbit

* **New Features**
  * Route-level pending UI: root routes can now specify their own loading placeholder.

* **Bug Fixes**
  * Pending-component selection now prefers a route's pending UI and falls back to the router default for consistent loading visuals.

* **Tests**
  * Added tests verifying route/root pending behavior and router-level fallback during async route loading.

### CODE REVIEW

File: packages/react-router/src/Matches.tsx [hunk 1]
```diff
@@ -41,10 +42,12 @@ declare module '@tanstack/router-core' {
 
 export function Matches() {
   const router = useRouter()
+  const rootRoute: AnyRoute = router.routesById['__root__']
```
Comment (TkDodo) [inline packages/react-router/src/Matches.tsx]: do we need to be defensive here and type this as `AnyRoute | undefined`. I think a `__root__` route must always exist ...

Comment (schiller-manuel) [reply packages/react-router/src/Matches.tsx]: please use `rootRouteId` from `@tanstack/router-core` instead of `__root__`

File: packages/react-router/tests/Matches.test.tsx [hunk 2]
```diff
@@ -121,3 +121,23 @@ test('when filtering useMatches by loaderData', async () => {
 
   expect(await screen.findByText('Incorrect Matches -')).toBeInTheDocument()
 })
+
+test('should show pendingComponent of root route', async () => {
+  const root = createRootRoute({
+    pendingComponent: () => <div>root pending...</div>,
```
Comment (schiller-manuel) [inline packages/react-router/tests/Matches.test.tsx]: please use `data-testid` and getByTestId or similar methods instead of looking for textual matches

File: packages/react-router/tests/Matches.test.tsx [hunk 3]
```diff
@@ -121,3 +121,23 @@ test('when filtering useMatches by loaderData', async () => {
...
+    loader: async () => {
+      await new Promise((r) => setTimeout(r, 50))
+    },
+    component: () => 'root content',
+  })
+  const router = createRouter({
```
Comment (schiller-manuel) [inline packages/react-router/tests/Matches.test.tsx:133]: same here

File: packages/react-router/src/Matches.tsx (hunk 1 above)
Comment (SeanCassiere) [reply packages/react-router/src/Matches.tsx]: and to answer your question, the answer is probably not, since a root route must always be present, but if it helps silence typescript then a `!` assertion or a `throw Error` should be fine.

Comment (TkDodo) [reply packages/react-router/src/Matches.tsx]: done: 74a38350

File: packages/react-router/tests/Matches.test.tsx (hunk 2 above)
Comment (TkDodo) [reply packages/react-router/tests/Matches.test.tsx]: done: 6fc6e2b6
