### PR TITLE
fix: Links always scroll to URL hash on hover (#5930) 

### LINKED ISSUE #5930: Links always scroll to URL hash on hover
### Which project does this relate to?

Router

### Describe the bug

After an update of react router a bug was introduced to our application. When there is a hash fragment in the URL to scroll to a specific headline, a scroll will be triggered as soon as any react router link on the page is hovered. I pinned it down to the last working version of react router that is 1.134.18. The next version on NPM is 1.134.20, which breaks the behaviour already. So I would suggest, the bug was intoduced in 1.134.19 or 1.134.20

### Your Example Website or App

https://stackblitz.com/edit/github-nsuiogjw?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Click on "About" link
2. Click on "To hash" link
3. Scroll back up again
4. Hover the cursor over the "Home" link

### Expected behavior

Result will be: Browser scrolls to the hash position
Expected is: No scroll at all when moving the cursor over a link.

### Screenshots or Videos

_No response_

### Platform

- Router Version: 1.134.20 - 1.139.0
- OS: Windows
- Browser: Brave
- Browser Version: latest
- Bundler: vite
- Bundler Version: latest

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Shreyas-Sarkar**
closes #5930

# Fix: Prevent hash scroll on preload-only transitions by gating handleHashScroll to true navigations

## What was the issue (#5930)

Hovering a Link with defaultPreload set to "intent" (or any programmatic preload) caused the router to trigger a hash scroll even though no navigation occurred. This resulted in the page unexpectedly jumping to an element associated with a hash fragment (for example, #id) when the user only hovered over a link.

In versions prior to v1.134.19, this did not occur. Between v1.134.18 and v1.134.20, router-core began running updateMatch inside router.startTransition. As a result, framework adapters (React and Solid) emitted onResolved during preload transitions. Both adapters unconditionally called handleHashScroll inside onResolved, so preloads triggered hash scrolling despite no URL change.

This caused the following behavior:

1. Navigate to a page containing a hash target.
2. Scroll down the page.
3. Hover any Link to trigger preload.
4. The page jumps back to the hash position even though no navigation occurred.

## The fix

In both framework Transitioner implementations (React and Solid):

1. Compute changeInfo using getLocationChangeInfo once during resolution.
2. Continue emitting onResolved using this changeInfo.
3. Only invoke handleHashScroll(router) when changeInfo.hrefChanged is true, ensuring that hash scrolling occurs only after an actual URL change.
4. No changes were made to router-core or scroll-restoration internals.

This restores the intended behavior:

- Hash scrolling occurs after real navigations.
- Preload-only transitions do not trigger any scrolling.
- Scroll restoration, SSR behavior, and navigation semantics remain unchanged.

## Summary by CodeRabbit

* **New Features**
  * Added /hover-preload-hash route to React and Solid apps.

* **Bug Fixes**
  * Hash scrolling now only triggers when the navigation target actually changes, avoiding unexpected scrolls during intent preloads.

* **Tests**
  * Added end-to-end tests validating hash-scroll behavior with hover-preload interactions.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by Shreyas-Sarkar** [comment]
@birkskyum It reflects the changed files. Please review this PR.

**Comment by birkskyum** [comment]
Great! could we add a test for this based on the issue reproduction to avoid regressions later?

**Comment by Shreyas-Sarkar** [comment]
@birkskyum  Thanks for the review. I can add a test, but I haven't written tests in this repo before, so I’m not sure about the expected location. Should this go inside the existing `app.spec.ts`, or should I create a new test file specifically for this hash-scroll regression case?

**Comment by birkskyum** [comment]
In the e2e/react-router/basic-file-based/ (same for solid) you can add a new route and test file there

**Comment by Shreyas-Sarkar** [comment]
I'll add the tests in e2e/react-router/basic-file-based/tests/ and same for solid-router. Thanks for the help!

**Comment by Shreyas-Sarkar** [comment]
@birkskyum I added descriptive tests. Please review.

**Comment by Shreyas-Sarkar** [comment]
@birkskyum fixed errors. Please Review.

**Comment by schiller-manuel** [comment]
not so sure if this is the actual fix here. need to discuss with @birkskyum

File: e2e/solid-router/basic-file-based/src/routes/lazy-page.tsx [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+
+export const Route = createFileRoute('/lazy-page')({
+  component: LazyPage,
+})
+
+function LazyPage() {
+  return (
+    <div class="p-2">
+      <h3>Lazy Loaded Page</h3>
+      <p>This page was loaded lazily.</p>
```
Comment (schiller-manuel) [inline e2e/solid-router/basic-file-based/src/routes/lazy-page.tsx]: lazy loaded how? why would it matter for this issue?

File: e2e/solid-router/basic-file-based/tests/hover-preload-hash.spec.ts [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+  // Go to a page with a hash target at the bottom
+  await page.goto(toRuntimePath('/normal-page#at-the-bottom'))
+  await expect(page.getByTestId('at-the-bottom')).toBeInViewport()
+
+  // Scroll up so the hash target is no longer in view
+  await page.evaluate(() => window.scrollBy(0, -300))
+  await expect(page.getByTestId('at-the-bottom')).not.toBeInViewport()
+
+  // Hover a header link to trigger intent preload (should NOT change scroll)
+  await page.getByRole('link', { name: 'Head-/lazy-page' }).hover()
```
Comment (schiller-manuel) [inline e2e/solid-router/basic-file-based/tests/hover-preload-hash.spec.ts]: always use test ids to locate elements

**Review by birkskyum — APPROVED** [review]

**Comment by Shreyas-Sarkar** [comment]
@birkskyum Thank you!
